# Generated by Django 5.2.6 on 2025-09-29 15:25

import recept.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', recept.models.UserManager()),
            ],
        ),
    ]
