# Generated by Django 5.2.6 on 2025-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован')], default='draft', help_text='Статус рецепта: черновик или опубликован', max_length=10),
        ),
        migrations.DeleteModel(
            name='RecipeStatus',
        ),
    ]
