# Generated by Django 5.2.7 on 2025-10-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0002_alter_user_managers'),
        ('recept', '0002_recipe_status_delete_recipestatus'),
    ]

    operations = [
    ]
