# Generated by Django 5.2.7 on 2025-10-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recept', '0003_merge_20251012_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Комментарии администратора при отклонении', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Калорийность на порцию', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('pending', 'На модерации'), ('rejected', 'Отклонен')], default='draft', help_text='Статус рецепта', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
